version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 123
        POSTGRES_DB: nest
    networks:
      - dev-network
  test-db:
    image: postgres:13
    ports:
      - "5434:5434"
    command: -p 5434
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - test-network
networks:
  dev-network:
    driver: bridge
  test-network:
    driver: bridge
